### ISSUE TITLE
HTML5 Support Status

### ISSUE THREAD

**Issue by soundyogi** [fmod/ue4integration#25]
Hi!
Is html5 supported? If not how could I achieve it?

I get the following ue4 Chrome Launch Error:

LogPlayLevel:   ERROR: Unable to instantiate module 'FMODStudio': System.Exception: Unsupported platform HTML5

Related:
http://www.fmod.org/public/js/
and
http://www.fmod.org/documentation/#content/generated/platform_js/basics.html

Thanks!

**Comment by fmod-mathew** [comment]
We have no plans for supporting HTML5 within UE4. Epic have largely abandoned the project pushing the platform support out to community managed GitHub. Additionally, I believe the source code is frozen at 4.24 and hasn't progressed since then so it seems largely a dead end. If Epic resumes active development of HTML5 we'll reconsider support it.
